/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package View;

/**
 *
 * @author manu_
 */
public class mainWindow extends java.awt.Frame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        canvasContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        executeSecuenceButton = new javax.swing.JButton();
        stepSecuenceButton = new javax.swing.JButton();
        addAFNDButton = new javax.swing.JButton();
        addAFDButton = new javax.swing.JButton();
        showAFDButton = new javax.swing.JButton();
        secuenceTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        showAFNDButton = new javax.swing.JButton();
        openFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        moreAFDButton = new javax.swing.JButton();
        moreAFNDButton = new javax.swing.JButton();
        enterSecuenceButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(canvasContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 500));

        console.setColumns(20);
        console.setRows(5);
        console.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        console.setEnabled(false);
        jScrollPane1.setViewportView(console);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 340, 210));

        executeSecuenceButton.setText("Ejecutar");
        executeSecuenceButton.setActionCommand("executeSecuence");
        jPanel1.add(executeSecuenceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 450, 160, 60));

        stepSecuenceButton.setText("Paso");
        stepSecuenceButton.setActionCommand("stepSecuence");
        jPanel1.add(stepSecuenceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 160, 60));

        addAFNDButton.setText("Añadir AFND");
        addAFNDButton.setActionCommand("addAFND");
        jPanel1.add(addAFNDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 130, 40));

        addAFDButton.setText("Añadir AFD");
        addAFDButton.setActionCommand("addAFD");
        jPanel1.add(addAFDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 130, 40));

        showAFDButton.setText("Mostrar AFD");
        showAFDButton.setActionCommand("showAFD");
        jPanel1.add(showAFDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 230, 130, 40));
        jPanel1.add(secuenceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 200, -1));

        jLabel1.setText("Indica la secuencia:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, -1, -1));

        showAFNDButton.setText("Mostrar AFND");
        showAFNDButton.setToolTipText("");
        showAFNDButton.setActionCommand("showAFND");
        jPanel1.add(showAFNDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 280, 130, 40));

        openFileButton.setText("Abrir fichero");
        openFileButton.setActionCommand("openFile");
        jPanel1.add(openFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 130, 40));

        saveFileButton.setText("Guardar fichero");
        saveFileButton.setActionCommand("saveFile");
        jPanel1.add(saveFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, 130, 40));

        moreAFDButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        moreAFDButton.setText("+");
        moreAFDButton.setActionCommand("moreAFD");
        jPanel1.add(moreAFDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 60, 40));

        moreAFNDButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        moreAFNDButton.setText("+");
        moreAFNDButton.setActionCommand("moreAFND");
        jPanel1.add(moreAFNDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 280, 60, 40));

        enterSecuenceButton.setText("Introducir");
        enterSecuenceButton.setActionCommand("enterSecuence");
        jPanel1.add(enterSecuenceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1085, 420, 130, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addAFDButton;
    public javax.swing.JButton addAFNDButton;
    public javax.swing.JPanel canvasContainer;
    public javax.swing.JTextArea console;
    public javax.swing.JButton enterSecuenceButton;
    public javax.swing.JButton executeSecuenceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton moreAFDButton;
    public javax.swing.JButton moreAFNDButton;
    public javax.swing.JButton openFileButton;
    public javax.swing.JButton saveFileButton;
    public javax.swing.JTextField secuenceTextField;
    public javax.swing.JButton showAFDButton;
    public javax.swing.JButton showAFNDButton;
    public javax.swing.JButton stepSecuenceButton;
    // End of variables declaration//GEN-END:variables
}
